# Generated by Django 3.1.5 on 2021-01-09 11:25

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(choices=[('whiteboard', 'Whiteboard'), ('chem', 'Chemical Drawing'), ('text', 'Text Document')], max_length=10, verbose_name='Type')),
                ('content', models.FileField(upload_to=core.models.user_directory_path, verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('thumb', models.ImageField(blank=True, default=None, null=True, upload_to=functools.partial(core.models.user_directory_path, *(), **{'thumb': True}), verbose_name='Thumbnail')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['owner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('content', models.TextField(verbose_name='Content')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molecules', to='core.file', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Molecule',
                'verbose_name_plural': 'Molecules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Folder')),
                ('public', models.BooleanField(blank=True, default=False, verbose_name='Public')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='core.folder', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['owner', 'name'],
            },
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.folder', verbose_name='Folder'),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
