# Generated by Django 3.1.5 on 2021-01-09 11:39

import core.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pdf',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=functools.partial(core.models.user_directory_path, *(), **{'subpath': 'pdf'}), verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='file',
            name='thumb',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=functools.partial(core.models.user_directory_path, *(), **{'subpath': 'thumbs'}), verbose_name='Thumbnail'),
        ),
    ]
