# Generated by Django 3.1.5 on 2021-01-18 08:56

import core.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fileshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='CKUploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='', verbose_name=functools.partial(core.models.user_directory_path, *(), **{'subpath': 'ck_images'}))),
            ],
        ),
    ]
