# Generated by Django 3.1.5 on 2021-01-18 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20210118_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckuploadimage',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
